# Generated by Django 4.0.3 on 2022-10-14 16:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='fitness_goal',
        ),
        migrations.RemoveField(
            model_name='target',
            name='weight_goal',
        ),
        migrations.AlterField(
            model_name='target',
            name='carbohydrate',
            field=models.DecimalField(decimal_places=1, default=260, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='carbohydrate (g)'),
        ),
        migrations.AlterField(
            model_name='target',
            name='fat',
            field=models.DecimalField(decimal_places=1, default=70, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='fat (g)'),
        ),
        migrations.AlterField(
            model_name='target',
            name='fibre',
            field=models.DecimalField(decimal_places=1, default=30, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='fibre (g)'),
        ),
        migrations.AlterField(
            model_name='target',
            name='protein',
            field=models.DecimalField(decimal_places=1, default=50, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='protein (g)'),
        ),
        migrations.AlterField(
            model_name='target',
            name='salt',
            field=models.DecimalField(decimal_places=2, default=6, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='salt (g)'),
        ),
        migrations.AlterField(
            model_name='target',
            name='saturates',
            field=models.DecimalField(decimal_places=1, default=20, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='saturates (g)'),
        ),
        migrations.AlterField(
            model_name='target',
            name='sugars',
            field=models.DecimalField(decimal_places=1, default=90, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='sugars (g)'),
        ),
    ]
