# Generated by Django 4.1.2 on 2022-10-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0005_alter_target_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="target",
            options={"ordering": ["-created_at"]},
        ),
    ]
