# Generated by Django 4.1.2 on 2022-10-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0006_alter_target_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="target",
            name="calculation_method",
            field=models.CharField(
                choices=[
                    ("CUS", "Custom"),
                    ("DEF", "Default"),
                    ("GRA", "Grams per kg"),
                    ("PER", "Percentage"),
                    ("REC", "Recommended"),
                ],
                default="DEF",
                help_text="Calculation method used to set your calorie and macronutrient targets.",
                max_length=3,
                verbose_name="calculation method",
            ),
        ),
    ]
