# Generated by Django 4.1.2 on 2022-10-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0003_alter_profile_options_alter_profile_activity_level_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="estimated_date_of_birth",
        ),
    ]
