# Generated by Django 4.1.2 on 2022-10-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_remove_profile_bio_remove_profile_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="goal",
            field=models.CharField(
                choices=[
                    ("LW", "Lose Weight"),
                    ("GW", "Build Muscle"),
                    ("MW", "Maintain Weight"),
                ],
                default="LW",
                max_length=2,
                verbose_name="goal",
            ),
        ),
    ]
