# Generated by Django 4.1.2 on 2022-10-16 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_alter_profile_goal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_initial_setup",
        ),
    ]
