# Generated by Django 4.1.2 on 2022-10-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user has verified their account via email after registering.",
            ),
        ),
    ]
