# Generated by Django 4.1.2 on 2022-10-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Has the user verified their account via email after registering.",
            ),
        ),
    ]
