# Generated by Django 4.1.2 on 2022-10-16 13:35

import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "This username is unavailable."},
                max_length=30,
                unique=True,
                validators=[apps.users.validators.UsernameValidator()],
            ),
        ),
    ]
