# Generated by Django 4.1.2 on 2022-10-15 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("progress", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="progress",
            options={
                "ordering": ("-date",),
                "verbose_name": "progress",
                "verbose_name_plural": "progress",
            },
        ),
        migrations.RemoveField(
            model_name="progress",
            name="site",
        ),
        migrations.AlterField(
            model_name="progress",
            name="energy_burnt",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="progress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
