# Generated by Django 4.1.7 on 2023-03-04 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseplan',
            old_name='exercise',
            new_name='movement',
        ),
    ]
