# Generated by Django 4.1.7 on 2023-03-05 05:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0002_rename_exercise_exerciseplan_movement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutplan',
            options={'ordering': ('training_plan', 'day', 'order')},
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='rest',
            field=models.PositiveIntegerField(default=60, help_text='Post-set rest time in seconds.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='description',
            field=models.TextField(default='-', max_length=1000),
            preserve_default=False,
        ),
    ]
