# Generated by Django 4.1.2 on 2023-02-04 22:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible_meals', models.PositiveIntegerField(default=6, validators=[django.core.validators.MaxValueValidator(6)])),
                ('meal_1_name', models.CharField(default='Breakfast', max_length=25)),
                ('meal_2_name', models.CharField(default='Morning Snack', max_length=25)),
                ('meal_3_name', models.CharField(default='Lunch', max_length=25)),
                ('meal_4_name', models.CharField(default='Afternoon Snack', max_length=25)),
                ('meal_5_name', models.CharField(default='Dinner', max_length=25)),
                ('meal_6_name', models.CharField(default='Evening Snack', max_length=25)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s_created_query', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', related_query_name='%(app_label)s_%(class)s_updated_query', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
