# Generated by Django 4.1.2 on 2023-02-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0002_remove_userfollowing_unique_following_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollowing',
            options={'ordering': ('id',)},
        ),
    ]
