# Generated by Django 4.1.2 on 2022-10-17 08:45

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diet_targets", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailydiettarget",
            name="carbohydrate",
            field=models.DecimalField(
                decimal_places=1,
                default=260,
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
                verbose_name="carbohydrate (g)",
            ),
        ),
        migrations.AlterField(
            model_name="dailydiettarget",
            name="energy",
            field=models.PositiveIntegerField(
                default=2000, verbose_name="calories (kcal)"
            ),
        ),
        migrations.AlterField(
            model_name="dailydiettarget",
            name="fat",
            field=models.DecimalField(
                decimal_places=1,
                default=70,
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
                verbose_name="fat (g)",
            ),
        ),
        migrations.AlterField(
            model_name="dailydiettarget",
            name="fibre",
            field=models.DecimalField(
                decimal_places=1,
                default=30,
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
                verbose_name="fibre (g)",
            ),
        ),
        migrations.AlterField(
            model_name="dailydiettarget",
            name="protein",
            field=models.DecimalField(
                decimal_places=1,
                default=50,
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
                verbose_name="protein (g)",
            ),
        ),
        migrations.AlterField(
            model_name="dailydiettarget",
            name="salt",
            field=models.DecimalField(
                decimal_places=2,
                default=6,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
                verbose_name="salt (g)",
            ),
        ),
        migrations.AlterField(
            model_name="dailydiettarget",
            name="saturates",
            field=models.DecimalField(
                decimal_places=1,
                default=20,
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
                verbose_name="saturates (g)",
            ),
        ),
        migrations.AlterField(
            model_name="dailydiettarget",
            name="sugars",
            field=models.DecimalField(
                decimal_places=1,
                default=90,
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
                verbose_name="sugars (g)",
            ),
        ),
        migrations.AlterField(
            model_name="dailydiettarget",
            name="user",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
