# Generated by Django 4.1.2 on 2022-10-18 21:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet_targets", "0003_alter_dailydiettarget_carbohydrate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailydiettarget",
            name="carbohydrate",
            field=models.DecimalField(
                decimal_places=1,
                default=260,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
                verbose_name="carbohydrate (g)",
            ),
        ),
    ]
