# Generated by Django 4.0.3 on 2022-10-14 16:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False)),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='slug')),
                ('data_value', models.IntegerField(verbose_name='data value')),
                ('data_measurement', models.CharField(choices=[('g', 'g'), ('ml', 'ml'), ('srv', 'serving')], max_length=3, verbose_name='data measurement')),
                ('energy', models.PositiveIntegerField(verbose_name='calories (kcal)')),
                ('fat', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='fat (g)')),
                ('saturates', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='saturates (g)')),
                ('carbohydrate', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='carbohydrate (g)')),
                ('sugars', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='sugars (g)')),
                ('fibre', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='fibre (g)')),
                ('protein', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='protein (g)')),
                ('salt', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='salt (g)')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food', to='food.brand', verbose_name='brand')),
            ],
            options={
                'verbose_name': 'food',
                'verbose_name_plural': 'food',
                'ordering': ('name',),
            },
        ),
    ]
