# Generated by Django 4.1.2 on 2022-10-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"ordering": ("name",)},
        ),
    ]
