# Generated by Django 4.1.2 on 2023-02-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('food', '0003_alter_brand_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='categories',
            field=models.ManyToManyField(to='categories.category'),
        ),
    ]
