# Generated by Django 4.1.7 on 2023-03-05 17:37

import apps.food.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_brand_created_by_alter_brand_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.food.models.brand_directory_path),
        ),
    ]
