# Generated by Django 4.1.7 on 2023-03-22 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_auto_20230322_1710'),
        ('food', '0006_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='new_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='brands.brand'),
        ),
    ]
