# Generated by Django 4.1.7 on 2023-03-22 17:26

from django.db import migrations


def move_data(apps, schema_editor):
    Food = apps.get_model("food", "Food")
    NewBrand = apps.get_model("brands", "Brand")
    for obj in Food.objects.all():
        brand_name = obj.brand.name
        try:
            new_brand_obj = NewBrand.objects.get(name=brand_name)
            obj.new_brand_id = new_brand_obj.id
            obj.save()
        except:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0007_food_new_brand"),
    ]

    operations = [
        migrations.RunPython(
            move_data,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
