# Generated by Django 4.0.3 on 2022-10-14 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.DurationField(blank=True, help_text='total duration the of exercise.', null=True)),
                ('notes', models.TextField(blank=True, max_length=2500, null=True, verbose_name='exercise notes')),
            ],
            options={
                'verbose_name': 'exercise',
                'verbose_name_plural': 'exercises',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'movement',
                'verbose_name_plural': 'movements',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'muscle group',
                'verbose_name_plural': 'muscle groups',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(editable=False, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('rest', models.DurationField(blank=True, help_text='post set rest time in seconds.', null=True, verbose_name='rest (seconds)')),
                ('level', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True, verbose_name='speed (kph)')),
                ('distance', models.IntegerField(blank=True, null=True, verbose_name='distance (km)')),
                ('duration', models.DurationField(blank=True, help_text='total duration of the set.', null=True)),
                ('notes', models.TextField(blank=True, max_length=2500, null=True, verbose_name='set notes')),
            ],
            options={
                'verbose_name': 'set',
                'verbose_name_plural': 'sets',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField(blank=True, help_text='total duration of the workout.', null=True)),
                ('notes', models.TextField(blank=True, max_length=2500, null=True, verbose_name='workout notes')),
            ],
            options={
                'verbose_name': 'workout',
                'verbose_name_plural': 'workouts',
                'ordering': ('-date', '-id'),
            },
        ),
    ]
