# Generated by Django 4.1.7 on 2023-03-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ('created_at',)},
        ),
    ]
