# Generated by Django 4.0.3 on 2022-10-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('updated_at',)},
        ),
    ]
