# Generated by Django 4.1.3 on 2022-12-21 20:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0003_alter_item_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
            ),
        ),
    ]
